language: generic
sudo: required

branches:
    only:
        - master
        - develop

services:
    - docker

install:
    - docker build -t sbmlutils .

before_script:
    # test dependencies
    - sudo pip install -r requirements.txt
    - sudo pip install mock
    - sudo pip install nose
    - sudo pip install coverage
    - sudo pip install coveralls

#script:
#    - nosetests --with-coverage

#after_success:
#    - coveralls
