"""
Autogenerated ODE definition SBML file with sbmlutils (https://github.com/matthiaskoenig/sbmlutils.git).

    model: iri_liver

time: [min]
substance: [mmol]
extent: [mmol]
volume: [l]
area: [m^2]
length: [m]
"""
import numpy as np
import pandas as pd

def piecewise(*kwargs):
    """Piecewise function.
    piecewise      | x1, y1, [x2, y2,] [...] [z] | A piecewise function: if (y1), x1.  Otherwise, if (y2), x2, etc.  Otherwise, z.
    """
    for k in np.floor(len(kwargs)/2.0):
        if kwargs[k+1]:
            return kwargs[k]
    if len(kwargs) % 2 == 1:
        return kwargs[-1]


# -------------------
# ids
# -------------------
xids = ["adp", "alt", "alt_ext", "ast", "ast_ext", "atp", "glc", "glc_ext", "lac", "lac_ext", "nad", "nadh", "necrosis", "o2", "o2_ext", "pyr", "ros", "tsim", ]
pids = ["ATPU_Km_atp", "ATPU_Vmax", "GLC2PYR_Ki_atp", "GLC2PYR_Km_adp", "GLC2PYR_Km_glc", "GLC2PYR_Vmax", "GLC2PYR_n_atp", "GLCIM_Km_glc", "GLCIM_Vmax", "LACEX_Km_lac", "LACEX_Vmax", "LDH_Ka_nadh", "LDH_Keq", "LDH_Km_lac", "LDH_Km_pyr", "LDH_Vmax", "O2IM_Km_o2", "O2IM_Vmax", "OXPHOS_Km_adp", "OXPHOS_Km_nadh", "OXPHOS_Km_o2", "OXPHOS_Vmax", "PROTEINR_k", "R", "ROSP_Vmax", "TCA_Km_nad", "TCA_Km_pyr", "TCA_Vmax", "Vext", "Vli", "Vmem", "cf_dimensionless", "f_Ea", "f_scale", "necrosis_atp_threshold", "ros_o2_threshold", "temperature", "temperature_ref", ]
yids = ["f_temperature", "necrosis", "ALTR", "ASTR", "ATPU", "GLC2PYR", "GLCIM", "LACEX", "LDH", "O2IM", "OXPHOS", "ROSD", "ROSP", "TCA", ]

# -------------------
# initial conditions
# -------------------
x0 = np.array([
    1.0,     # [0] adp [mmol/l] ADP in Vli
    1.0,     # [1] alt [mmol/l] ALT (liver) in Vli
    0.0,     # [2] alt_ext [mmol/l] ALT in Vext
    0.7,     # [3] ast [mmol/l] AST (liver) in Vli
    0.0,     # [4] ast_ext [mmol/l] AST in Vext
    3.0,     # [5] atp [mmol/l] ATP (liver) in Vli
    5.0,     # [6] glc [mmol/l] D-glucose (liver) in Vli
    5.0,     # [7] glc_ext [mmol/l] D-glucose (plasma) in Vext
    1.0,     # [8] lac [mmol/l] D-lactate (liver) in Vli
    1.0,     # [9] lac_ext [mmol/l] D-lactate (plasma) in Vext
    0.1,     # [10] nad [mmol/l] NAD in Vli
    3.9,     # [11] nadh [mmol/l] NADH in Vli
    0.0,     # [12] necrosis [-] condition for necrosis depending on ATP in Vli
    1.2,     # [13] o2 [mmol/l] dioxygen (liver) in Vli
    1.2,     # [14] o2_ext [mmol/l] dioxygen (plasma) in Vext
    0.8,     # [15] pyr [mmol/l] D-pyruvate (liver) in Vli
    0.0,     # [16] ros [mmol/l] reactive oxygen species (ROS) in Vli
    0.0,     # [17] tsim [min] simulation time
])

# -------------------
# parameters
# -------------------
p = np.array([
    0.01,     # [0] ATPU_Km_atp [mmol/l] Km atp atp usage
    0.1,     # [1] ATPU_Vmax [mmol/min/l] Vmax lactate dehydrogenase
    1.5,     # [2] GLC2PYR_Ki_atp [mmol/l] Ki atp glycolysis
    0.01,     # [3] GLC2PYR_Km_adp [mmol/l] Km adp glycolysis
    0.5,     # [4] GLC2PYR_Km_glc [mmol/l] Km glc glycolysis
    0.2,     # [5] GLC2PYR_Vmax [mmol/min/l] Vmax glycolysis
    4.0,     # [6] GLC2PYR_n_atp [-] n atp glycolysis
    0.1,     # [7] GLCIM_Km_glc [mmol/l] Km S import
    100.0,     # [8] GLCIM_Vmax [mmol/min/l] Vmax S import
    0.5,     # [9] LACEX_Km_lac [mmol/l] Km lac import
    100.0,     # [10] LACEX_Vmax [mmol/min/l] Vmax lactate export
    0.1,     # [11] LDH_Ka_nadh [mmol/l] Ki nadh lactate dehydrogenase
    1.5,     # [12] LDH_Keq [-] Keq lactate dehydrogenase
    1.0,     # [13] LDH_Km_lac [mmol/l] Km lac lactate dehydrogenase
    1.0,     # [14] LDH_Km_pyr [mmol/l] Km pyr lactate dehydrogenase
    1.0,     # [15] LDH_Vmax [mmol/min/l] Vmax lactate dehydrogenase
    0.1,     # [16] O2IM_Km_o2 [mmol/l] Km S import
    100.0,     # [17] O2IM_Vmax [mmol/min/l] Vmax O2 import
    0.05,     # [18] OXPHOS_Km_adp [mmol/l] Km adp oxidative phosphorylation
    0.05,     # [19] OXPHOS_Km_nadh [mmol/l] Km nadh oxidative phosphorylation
    0.05,     # [20] OXPHOS_Km_o2 [mmol/l] Km o2 oxidative phosphorylation
    0.03,     # [21] OXPHOS_Vmax [mmol/min/l] Vmax glycolysis
    0.2,     # [22] PROTEINR_k [1/min] Vmax protein release
    8.314,     # [23] R [kg*m^2/s^2/mol/K] Rydberg constant [J/mol/K]
    0.005,     # [24] ROSP_Vmax [mmol/min/l] Vmax factor oxidative phosphorylation
    0.01,     # [25] TCA_Km_nad [mmol/l] Km nad oxidative phosphorylation
    0.1,     # [26] TCA_Km_pyr [mmol/l] Km glc oxidative phosphorylation
    0.01,     # [27] TCA_Vmax [mmol/min/l] Vmax glycolysis
    0.1,     # [28] Vext [l] plasma
    1.5,     # [29] Vli [l] liver
    1.0,     # [30] Vmem [m^2] plasma membrane
    1.0,     # [31] cf_dimensionless [1/mmol] conversion factor for dimensionless species
    12.0,     # [32] f_Ea [-] factor activation energy Ea
    2.0,     # [33] f_scale [-] factor for speedup/slowdown of system
    0.1,     # [34] necrosis_atp_threshold [mmol/l] E50 ATP threshold for necrosis to occur [mM]
    0.1,     # [35] ros_o2_threshold [mmol/l] O2 threshold for ROS production [mM]
    310.15,     # [36] temperature [K] temperature [K]
    310.15,     # [37] temperature_ref [K] reference temperature (37°C) [K]
])


def f_dxdt(x: np.ndarray, t: float, p: np.ndarray) -> np.ndarray:
    """ODE system."""
    f_temperature = p[33] * exp(-(p[32] * p[23] * p[37]) / (p[23] * p[36])) / exp(-(p[32] * p[23] * p[37]) / (p[23] * p[37]))      # [0] f_temperature [-] temperature dependence of reaction rates
    necrosis = piecewise(1, x[5] < p[34], 0)      # [1] necrosis [] condition for necrosis depending on ATP
    ALTR = f_temperature * x[12] * p[29] * p[22] * x[1]      # [2] ALTR [mmol/min] ALT release (ALTR)
    ASTR = f_temperature * x[12] * p[29] * p[22] * x[3]      # [3] ASTR [mmol/min] AST release (ASTR)
    ATPU = f_temperature * p[29] * p[1] * x[5] / (p[0] + x[5])      # [4] ATPU [mmol/min] ATP usage (ATPU)
    GLC2PYR = (f_temperature * (1 - x[12]) * p[29] * (p[2] / x[5])**p[6] * p[5] * x[6] / (x[6] + p[4])) * x[0] / (x[0] + p[3])      # [5] GLC2PYR [mmol/min] glycolysis
    GLCIM = (f_temperature * (1 - x[12]) * p[29] * p[8] / p[7]) * (x[7] - x[6]) / (1 + x[7] / p[7] + x[6] / p[7])      # [6] GLCIM [mmol/min] glucose import (GLCIM)
    LACEX = (f_temperature * (1 - x[12]) * p[29] * p[10] / p[9]) * (x[8] - x[9]) / (1 + x[9] / p[9] + x[8] / p[9])      # [7] LACEX [mmol/min] lactate export (LACEX)
    LDH = (f_temperature * (1 - x[12]) * p[29] * p[15] / p[14]) * (1 + x[11] / p[11]) * (x[15] - x[8] / p[12]) / (1 + x[15] / p[14] + x[8] / p[13])      # [8] LDH [mmol/min] lactate dehydrogenase (LDH)
    O2IM = (f_temperature * (1 - x[12]) * p[29] * p[17] / p[16]) * (x[14] - x[13]) / (1 + x[14] / p[16] + x[13] / p[16])      # [9] O2IM [mmol/min] oxygen import (O2IM)
    OXPHOS = ((f_temperature * (1 - x[12]) * p[29] * p[21] * x[11] / (x[11] + p[19])) * x[13] / (x[13] + p[20])) * x[0] / (x[0] + p[18])      # [10] OXPHOS [mmol/min] oxidative phosphorylation (OXPHOS)
    ROSD = f_temperature * (1 - x[12]) * p[29] * p[24] * x[16] / p[35]      # [11] ROSD [mmol/min] reactive oxygen detoxification (ROSD)
    ROSP = (f_temperature * (1 - x[12]) * p[29] * p[24] * x[11] / (x[11] + p[19])) * piecewise(1, x[13] < p[35], 0)      # [12] ROSP [mmol/min] reactive oxygen production (ROSP)
    TCA = (f_temperature * (1 - x[12]) * p[29] * p[27] * x[15] / (x[15] + p[26])) * x[10] / (x[10] + p[25])      # [13] TCA [mmol/min] tca cycle (TCA)

    # ode
    return np.ndarray([
        -2 * GLC2PYR / p[29] + ATPU / p[29] - 3 * OXPHOS / p[29],       # [0] adp [mmol/l] ADP
        -ALTR / p[29],       # [1] alt [mmol/l] ALT (liver)
        ALTR / p[28],       # [2] alt_ext [mmol/l] ALT
        -ASTR / p[29],       # [3] ast [mmol/l] AST (liver)
        ASTR / p[28],       # [4] ast_ext [mmol/l] AST
        (2 * GLC2PYR / p[29] - ATPU / p[29]) + 3 * OXPHOS / p[29],       # [5] atp [mmol/l] ATP (liver)
        GLCIM / p[29] - GLC2PYR / p[29],       # [6] glc [mmol/l] D-glucose (liver)
        -GLCIM / p[28],       # [7] glc_ext [mmol/l] D-glucose (plasma)
        -LACEX / p[29] + LDH / p[29],       # [8] lac [mmol/l] D-lactate (liver)
        LACEX / p[28],       # [9] lac_ext [mmol/l] D-lactate (plasma)
        -6 * TCA / p[29] + OXPHOS / p[29],       # [10] nad [mmol/l] NAD
        6 * TCA / p[29] - OXPHOS / p[29],       # [11] nadh [mmol/l] NADH
        0,       # [12] necrosis [-] condition for necrosis depending on ATP
        O2IM / p[29] - 0.5 * OXPHOS / p[29],       # [13] o2 [mmol/l] dioxygen (liver)
        -O2IM / p[28],       # [14] o2_ext [mmol/l] dioxygen (plasma)
        GLC2PYR / p[29] - LDH / p[29] - TCA / p[29],       # [15] pyr [mmol/l] D-pyruvate (liver)
        ROSP / p[29] - ROSD / p[29],       # [16] ros [mmol/l] reactive oxygen species (ROS)
        1,       # [17] tsim [min] simulation time
    ])


def f_y(x: np.ndarray, t: float, p: np.ndarray) -> np.ndarray:
    """Calculate y.
    :param x: state vector
    :param t: time
    :param p: parameter vector
    :return:
    """

    f_temperature = p[33] * exp(-(p[32] * p[23] * p[37]) / (p[23] * p[36])) / exp(-(p[32] * p[23] * p[37]) / (p[23] * p[37]))  # [0] f_temperature  [-] temperature dependence of reaction rates
    necrosis = piecewise(1, x[5] < p[34], 0)  # [1] necrosis  [] condition for necrosis depending on ATP
    ALTR = f_temperature * x[12] * p[29] * p[22] * x[1]  # [2] ALTR  [mmol/min] ALT release (ALTR)
    ASTR = f_temperature * x[12] * p[29] * p[22] * x[3]  # [3] ASTR  [mmol/min] AST release (ASTR)
    ATPU = f_temperature * p[29] * p[1] * x[5] / (p[0] + x[5])  # [4] ATPU  [mmol/min] ATP usage (ATPU)
    GLC2PYR = (f_temperature * (1 - x[12]) * p[29] * (p[2] / x[5])**p[6] * p[5] * x[6] / (x[6] + p[4])) * x[0] / (x[0] + p[3])  # [5] GLC2PYR  [mmol/min] glycolysis
    GLCIM = (f_temperature * (1 - x[12]) * p[29] * p[8] / p[7]) * (x[7] - x[6]) / (1 + x[7] / p[7] + x[6] / p[7])  # [6] GLCIM  [mmol/min] glucose import (GLCIM)
    LACEX = (f_temperature * (1 - x[12]) * p[29] * p[10] / p[9]) * (x[8] - x[9]) / (1 + x[9] / p[9] + x[8] / p[9])  # [7] LACEX  [mmol/min] lactate export (LACEX)
    LDH = (f_temperature * (1 - x[12]) * p[29] * p[15] / p[14]) * (1 + x[11] / p[11]) * (x[15] - x[8] / p[12]) / (1 + x[15] / p[14] + x[8] / p[13])  # [8] LDH  [mmol/min] lactate dehydrogenase (LDH)
    O2IM = (f_temperature * (1 - x[12]) * p[29] * p[17] / p[16]) * (x[14] - x[13]) / (1 + x[14] / p[16] + x[13] / p[16])  # [9] O2IM  [mmol/min] oxygen import (O2IM)
    OXPHOS = ((f_temperature * (1 - x[12]) * p[29] * p[21] * x[11] / (x[11] + p[19])) * x[13] / (x[13] + p[20])) * x[0] / (x[0] + p[18])  # [10] OXPHOS  [mmol/min] oxidative phosphorylation (OXPHOS)
    ROSD = f_temperature * (1 - x[12]) * p[29] * p[24] * x[16] / p[35]  # [11] ROSD  [mmol/min] reactive oxygen detoxification (ROSD)
    ROSP = (f_temperature * (1 - x[12]) * p[29] * p[24] * x[11] / (x[11] + p[19])) * piecewise(1, x[13] < p[35], 0)  # [12] ROSP  [mmol/min] reactive oxygen production (ROSP)
    TCA = (f_temperature * (1 - x[12]) * p[29] * p[27] * x[15] / (x[15] + p[26])) * x[10] / (x[10] + p[25])  # [13] TCA  [mmol/min] tca cycle (TCA)

    # --------------------------------------

    y = np.empty(shape=(14))
    y[0] = f_temperature  # [0] f_temperature  [-] temperature dependence of reaction rates
    y[1] = necrosis  # [1] necrosis  [] condition for necrosis depending on ATP
    y[2] = ALTR  # [2] ALTR  [mmol/min] ALT release (ALTR)
    y[3] = ASTR  # [3] ASTR  [mmol/min] AST release (ASTR)
    y[4] = ATPU  # [4] ATPU  [mmol/min] ATP usage (ATPU)
    y[5] = GLC2PYR  # [5] GLC2PYR  [mmol/min] glycolysis
    y[6] = GLCIM  # [6] GLCIM  [mmol/min] glucose import (GLCIM)
    y[7] = LACEX  # [7] LACEX  [mmol/min] lactate export (LACEX)
    y[8] = LDH  # [8] LDH  [mmol/min] lactate dehydrogenase (LDH)
    y[9] = O2IM  # [9] O2IM  [mmol/min] oxygen import (O2IM)
    y[10] = OXPHOS  # [10] OXPHOS  [mmol/min] oxidative phosphorylation (OXPHOS)
    y[11] = ROSD  # [11] ROSD  [mmol/min] reactive oxygen detoxification (ROSD)
    y[12] = ROSP  # [12] ROSP  [mmol/min] reactive oxygen production (ROSP)
    y[13] = TCA  # [13] TCA  [mmol/min] tca cycle (TCA)

    return y


def f_z(X, T, p):
    """ DataFrame of full timecourse of solution. """
    (Nt, Nx) = X.shape
    Ny = len(yids)
    Nz = 1 + Nx + Ny
    columns = ["time"] + xids + yids
    Z = np.empty(shape=(Nt, Nz))
    Z[:, 0] = T
    Z[:, 1:(Nx+1)] = X
    for kt in range(Nt):
        y = f_y(x=X[kt, :], t=T[kt], p=p)
        Z[kt, (Nx+1):] = y

    Z = pd.DataFrame(Z, columns=columns)
    return Z