# -------------------------------------------------------------------------------------
# Autogenerated ODE definition from SBML file with sbmlutils
# (https://github.com/matthiaskoenig/sbmlutils).
#
#    model: {{ model.getId() }}
# -------------------------------------------------------------------------------------

module {{ model.getId() }}
    export p, x0, f_dxdt, xids, pids, yids

    # ids
    xids = [{% for id in xids %}"{{ id }}"{% if not loop.last %}, {% endif %}{% endfor %}]
    pids = [{% for id in pids %}"{{ id }}"{% if not loop.last %}, {% endif %}{% endfor %}]

    # initial conditions
    x0 = [
    {% for id in xids %}
      {{ x0[id] }}{% if not loop.last %},{% endif %}      # x0[{{ loop.index }}] {{ id }}
    {% endfor %}
    ]

    # parameters
    p = [
    {% for id in pids %}
      {{ p[id] }}{% if not loop.last %},{% endif %}      # p[{{ loop.index }}] {{ id }}
    {% endfor %}
    ]

    # odes
    function f_dxdt(dx, x, p, t)
        {% for id in yids %}
        {{ id }} = {{ y[id] }}      # y[{{ loop.index }}] {{ id }}
        {% endfor %}

        {% for id in xids %}
        dx[{{loop.index}}] = {{ dx[id] }}     # dx[{{ loop.index }}] {{ id }}
        {% endfor %}

    end

end
