# -----------------------------------------------------------
# Autogenerated ODE definition from SBML file with sbmlutils.
#
#    model: {{ model.getId() }}
# -----------------------------------------------------------

template< typename RealType >
void GlycoReactionMK<RealType>::evaluateDerivative ( const aol::Vector<RealType> &ProfileOld, const RealType /*Time*/, aol::Vector<RealType> &ProfileTDeriv ) const {
  const RealType

    {% for id in pids %}
      float {{ id }} = {{ p[id] }};
    {% endfor %}

    {% for id in xids %}
    ProfileTDeriv[ this->{{id}} ] = {{ dx[id] }}

    {% endfor %}

}
