# Docker image with latest libsbml-develop branch python bindings
# build and run container
#   docker build --tag pylibnuml --file Dockerfile-pylibnuml .
#   docker run --name pylibnuml -it pylibnuml bash

FROM pylibsbml:latest

# checkout git
RUN mkdir /git

WORKDIR /code
COPY ./libnuml.sh /code/

RUN ./libnuml.sh
