# Docker image with latest libsedml-develop branch python bindings
# build and run container
#   docker build --tag pylibsedml --file Dockerfile-pylibsedml .
#   docker run --name pylibsedml -it pylibsedml bash

FROM pylibnuml:latest

WORKDIR /code
COPY ./libsedml.sh /code/

RUN ./libsedml.sh
