# Docker image with latest libsbml-develop branch python bindings
# build and run container
#   docker build --tag pysedml --file Dockerfile-pylibsedml .
#   docker run --name pysedml -it pylibsedml bash


FROM pylibsbml:latest

# checkout git
RUN mkdir /git

WORKDIR /code
COPY ./libnuml.sh /code/

RUN ./libnuml.sh
