# Docker image with latest libsbml-develop branch python bindings
# build and run container
#   docker build --tag pylibsbml --file Dockerfile-pylibsbml --no-cache .
#   docker build --tag pylibsbml --no-cache .
#   docker run --name pylibsbml -it pylibsbml bash
# connect pycharm
# settings -> interpreter -> docker -> sbmlutils:latest

FROM python:3.6
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y subversion cmake cmake-gui swig libxml2 libxml2-dev libbz2-dev zlib1g-dev

# checkout svn code
RUN mkdir /svn
WORKDIR /svn

# libsbml-stable
# RUN svn checkout --depth empty http://svn.code.sf.net/p/sbml/code/trunk sbml-code
# RUN svn update --quiet --set-depth infinity sbml-code/libsbml

# libsbml-experimental branch
RUN mkdir -p /svn/sbml-code
WORKDIR /svn/sbml-code
RUN svn checkout http://svn.code.sf.net/p/sbml/code/branches/libsbml-experimental libsbml

WORKDIR /code
COPY ./libsbml.sh /code/

RUN ./libsbml.sh
