# -----------------------------------------------------------
# Autogenerated ODE definition from SBML file with sbmlutils.
#
#    model: linear_chain
# -----------------------------------------------------------

# -------------------
# ids
# -------------------
xids <- c("S1", "S2", "S3", "S4")
pids <- c("cell", "k1", "k2", "k3")
yids <- c("J1", "J2", "J3")

# -------------------
# initial conditions
# -------------------
x0 = c(
  S1 = 10.0,      # [1]
  S2 = 0.0,      # [2]
  S3 = 0.0,      # [3]
  S4 = 0.0      # [4]
)

# -------------------
# parameters
# -------------------
p = c(
  cell = 1.0,      # [1]
  k1 = 0.1,      # [2]
  k2 = 0.1,      # [3]
  k3 = 0.1      # [4]
)


# -------------------
# dmod odes
# -------------------
dxdt_dmod <- c(
    S1 = "-(k1 * S1) / cell",   # [1]
    S2 = "k1 * S1 / cell - k2 * S2 / cell",   # [2]
    S3 = "k2 * S2 / cell - k3 * S3 / cell",   # [3]
    S4 = "k3 * S3 / cell"  # [4]
)

y_dmod <- c(
    J1 = "k1 * S1",   # [1]
    J2 = "k2 * S2",   # [2]
    J3 = "k3 * S3"  # [3]
)



# -------------------
# odes
# -------------------
f_dxdt <- function(t, x, p){
    # ODE system
    J1 = p[2] * x[1]      # [1] J1
    J2 = p[3] * x[2]      # [2] J2
    J3 = p[4] * x[3]      # [3] J3

    # ode
    list(c(
        dS1 = -J1 / p[1],
        dS2 = J1 / p[1] - J2 / p[1],
        dS3 = J2 / p[1] - J3 / p[1],
        dS4 = J3 / p[1]
    ))
}

f_y <- function(times, x, p){
    # Calculate y

    J1 = p[2] * x[1]  # [1] J1
    J2 = p[3] * x[2]  # [2] J2
    J3 = p[4] * x[3]  # [3] J3

    # --------------------------------------
    c(J1, J2, J3)
}


f_z <- function(times, X, p){
    # calculate z
    shape <- dim(X)
    Nt <- shape[1]
    Nx <- shape[2] - 1
    Ny = length(yids)
    Nz = 1 + Nx + Ny
    Z = matrix(, nrow=Nt, ncol=Nz)
    Z[,1] = times
    for (kx in seq(Nx)){
        Z[,(1+kx)] = X[,1+kx]
    }
    for (kt in seq(Nt)){
        y = f_y(t=times[kt], x=X[kt, 2:(Nx+1)], p=p)
        Z[kt, (2+Nx):Nz] = y
    }
    colnames(Z) <- c ("time", xids, yids)
    Z
}