#set document(title: [Elowitz2000 - Repressilator])
#set page(margin: 2cm)
#set text(size: 10pt)
#set par(justify: true)
#set heading(numbering: "1.")
// the equations of a section are one block, which breaks across pages
#show math.equation.where(block: true): set block(breakable: true)
#show math.equation.where(block: true): set par(leading: 0.9em)

#align(center, text(size: 16pt, weight: "bold")[Elowitz2000 - Repressilator])

Model `BIOMD0000000012`, SBML Level 2 Version 3, read from BIOMD0000000012\_urn.xml, written by sbmlutils 0.13.0.

Elowitz2000 - Repressilator

This model describes the deterministic version of the repressilator system.

The authors of this model (see reference) use three transcriptional repressor systems that are not part of any natural biological clock to build an oscillating network that they called the repressilator. The model system was induced in Escherichia coli.

In this system, LacI (variable X is the mRNA, variable PX is the protein) inhibits the tetracycline-resistance transposon tetR (Y, PY describe mRNA and protein). Protein tetR inhibits the gene Cl from phage Lambda (Z, PZ: mRNA, protein),and protein Cl inhibits lacI expression. With the appropriate parameter values this system oscillates.

This model is described in the article:

A synthetic oscillatory network of transcriptional regulators.

Elowitz MB, Leibler S.

Nature. 2000 Jan; 403(6767):335-338

Abstract:

Networks of interacting biomolecules carry out many essential functions in living cells, but the 'design principles' underlying the functioning of such intracellular networks remain poorly understood, despite intensive efforts including quantitative analysis of relatively simple systems. Here we present a complementary approach to this problem: the design and construction of a synthetic network to implement a particular function. We used three transcriptional repressor systems that are not part of any natural biological clock to build an oscillating network, termed the repressilator, in Escherichia coli. The network periodically induces the synthesis of green fluorescent protein as a readout of its state in individual cells. The resulting oscillations, with typical periods of hours, are slower than the cell-division cycle, so the state of the oscillator has to be transmitted from generation to generation. This artificial clock displays noisy behaviour, possibly because of stochastic fluctuations of its components. Such 'rational network design may lead both to the engineering of new cellular behaviours and to an improved understanding of naturally occurring networks.

The model is based upon the equations in Box 1 of the paper; however, these equations as printed are dimensionless, and the correct dimensions have been returned to the equations, and the parameters set to reproduce Figure 1C (left).

The original model was generated by B.E. Shapiro using Cellerator version 1.0 update 2.1127 using Mathematica 4.2 for Mac OS X (June 4, 2002), November 27, 2002 12:15:32, using (PowerMac,PowerPC, Mac OS X,MacOSX,Darwin).

Nicolas Le Novere provided a corrected version generated by SBMLeditor on Sun Aug 20 00:44:05 BST 2006. This removed the EmptySet species. Ran fine on COPASI 4.0 build 18.

Bruce Shapiro revised the model with SBMLeditor on 23 October 2006 20:39 PST. This defines default units and correct reactions. The original Cellerator reactions while being mathematically correct did not accurately reflect the intent of the authors. The original notes were mostly removed because they were mostly incorrect in the revised version. Tested with MathSBML 2.6.0.

Nicolas Le Novere changed the volume to 1 cubic micrometre, to allow for stochastic simulation.

Changed by Lukas Endler to use the average livetime of mRNA instead of its halflife and a corrected value of alpha and alpha0.

Moreover, the equations used in this model were clarified, cf. below.

The equations given in box 1 of the original publication are rescaled in three respects (lowercase letters denote the rescaled, uppercase letters the unscaled number of molecules per cell):

the time is rescaled to the average mRNA lifetime, t\_ave: τ = t/t\_ave

the mRNA concentration is rescaled to the translation efficiency eff: m = M/eff

the protein concentration is rescaled to Km: p = P/Km

α in the equations should be in units of rescaled proteins per promotor and cell, and β is the ratio of the protein to the mRNA decay rates or the ratio of the mRNA to the protein halflife.

In this version of the model α and β are calculated correspondingly to the article, while p and m where just replaced by P/Km resp. M/eff and all equations multiplied by 1/t\_ave. Also, to make the equations easier to read, commonly used variables derived from the parameters given in the article by simple rules were introduced.

The parameters given in the article were:

promotor strength (repressed) (tps\_repr): 5\*10 -4 transcripts/(promotor\*s)

promotor strength (full) (tps\_active): 0.5 transcripts/(promotor\*s)

mRNA half life, τ 1/2,mRNA: 2 min

protein half life, τ 1/2,prot: 10 min

K M: 40 monomers/cell

Hill coefficient n: 2

From these the following constants can be derived:

average mRNA lifetime (t\_ave): τ 1/2,mRNA /ln(2) = 2.89 min

mRNA decay rate (kd\_mRNA): ln(2)/ τ 1/2,mRNA = 0.347 min -1

protein decay rate (kd\_prot): ln(2)/ τ 1/2,prot

transcription rate (a\_tr): tps\_active\*60 = 29.97 transcripts/min

transcription rate (repressed) (a0\_tr): tps\_repr\*60 = 0.03 transcripts/min

translation rate (k\_tl): eff\*kd\_mRNA = 6.93 proteins/(mRNA\*min)

α : a\_tr\*eff\*τ 1/2,prot /(ln(2)\*K M) = 216.4 proteins/(promotor\*cell\*Km)

α 0: a0\_tr\*eff\*τ 1/2,prot /(ln(2)\*K M) = 0.2164 proteins/(promotor\*cell\*Km)

β : k\_dp/k\_dm = 0.2

Annotation by the Kinetic Simulation Algorithm Ontology (KiSAO):

To reproduce the simulations run published by the authors, the model has to be simulated with any of two different approaches. First, one could use a deterministic method (KISAO\_0000035) with continuous variables (KISAO\_0000018). One sample algorithm to use is the CVODE solver (KISAO\_0000019). Second, one could simulate the system using Gillespie's direct method (KISAO\_0000029), which is a stochastic method (KISAO\_0000036) supporting adaptive timesteps (KISAO\_0000041) and using discrete variables (KISAO\_0000016).

This model is hosted on BioModels Database and identified by: BIOMD0000000012.

To cite BioModels Database, please use: BioModels Database: An enhanced, curated and annotated resource for published quantitative kinetic models.

To the extent possible under law, all copyright and related or neighbouring rights to this encoded model have been dedicated to the public domain worldwide. Please refer to CC0 Public Domain Dedication for more information.

= Units

#table(
  columns: 6,
  stroke: none,
  column-gutter: 1.5em,
  table.hline(stroke: 0.8pt),
  table.header([*Time*], [*Substance*], [*Extent*], [*Volume*], [*Area*], [*Length*]),
  table.hline(stroke: 0.4pt),
  [min], [item], [item], [#text(ligatures: false)[fl]], [m#super[2]], [m],
  table.hline(stroke: 0.8pt),
)

= Compartments

#table(
  columns: (auto, auto, auto, auto, auto),
  stroke: none,
  align: (left, left, left, left, center),
  table.hline(stroke: 0.8pt),
  table.header([*Symbol*], [*Id*], [*Size*], [*Unit*], [*Constant*]),
  table.hline(stroke: 0.4pt),
  [$upright("cell")$], [`cell`], [$1$], [#text(ligatures: false)[fl]], [#sym.checkmark],
  table.hline(stroke: 0.8pt),
)

= Species

#table(
  columns: (auto, auto, 1fr, auto, auto, auto, 1fr),
  stroke: none,
  align: (left, left, left, left, left, left, left),
  table.hline(stroke: 0.8pt),
  table.header([*Symbol*], [*Id*], [*Name*], [*Compartment*], [*Value*], [*Unit*], [*Properties*]),
  table.hline(stroke: 0.4pt),
  [$upright("PX")$], [`PX`], [LacI protein], [$upright("cell")$], [$0$], [item], [amount],
  [$upright("PY")$], [`PY`], [TetR protein], [$upright("cell")$], [$0$], [item], [amount],
  [$upright("PZ")$], [`PZ`], [cI protein], [$upright("cell")$], [$0$], [item], [amount],
  [$X$], [`X`], [LacI mRNA], [$upright("cell")$], [$0$], [item], [amount],
  [$Y$], [`Y`], [TetR mRNA], [$upright("cell")$], [$20$], [item], [amount],
  [$Z$], [`Z`], [cI mRNA], [$upright("cell")$], [$0$], [item], [amount],
  table.hline(stroke: 0.8pt),
)

= Parameters

#table(
  columns: (auto, auto, 1fr, auto, auto),
  stroke: none,
  align: (left, left, left, left, center),
  table.hline(stroke: 0.8pt),
  table.header([*Symbol*], [*Id*], [*Name*], [*Value*], [*Constant*]),
  table.hline(stroke: 0.4pt),
  [$beta$], [`beta`], [beta], [], [],
  [$alpha_(0)$], [`alpha0`], [alpha0], [], [],
  [$alpha$], [`alpha`], [alpha], [], [],
  [$upright("eff")$], [`eff`], [translation efficiency], [$20$], [#sym.checkmark],
  [$n$], [`n`], [n], [$2$], [#sym.checkmark],
  [$upright("KM")$], [`KM`], [KM], [$40$], [#sym.checkmark],
  [$tau_("mRNA")$], [`tau_mRNA`], [mRNA half life], [$2$], [#sym.checkmark],
  [$tau_("prot")$], [`tau_prot`], [protein half life], [$10$], [#sym.checkmark],
  [$t_("ave")$], [`t_ave`], [average mRNA life time], [], [],
  [$upright("kd")_("mRNA")$], [`kd_mRNA`], [kd\_mRNA], [], [],
  [$upright("kd")_("prot")$], [`kd_prot`], [kd\_prot], [], [],
  [$k_("tl")$], [`k_tl`], [k\_tl], [], [],
  [$a_("tr")$], [`a_tr`], [a\_tr], [], [],
  [$upright("ps")_("a")$], [`ps_a`], [tps\_active], [$0.5$], [#sym.checkmark],
  [$upright("ps")_(0)$], [`ps_0`], [tps\_repr], [$0.0005$], [#sym.checkmark],
  [$upright("a0")_("tr")$], [`a0_tr`], [a0\_tr], [], [],
  table.hline(stroke: 0.8pt),
)

= Initial assignments and assignment rules

The assignment rules hold at every time $t$:

$ t_("ave") &= (tau_("mRNA"))/(ln(2)) \
  beta &= (tau_("mRNA"))/(tau_("prot")) \
  k_("tl") &= (upright("eff"))/(t_("ave")) \
  a_("tr") &= (upright("ps")_("a") - upright("ps")_(0)) dot 60 \
  upright("a0")_("tr") &= upright("ps")_(0) dot 60 \
  upright("kd")_("prot") &= (ln(2))/(tau_("prot")) \
  upright("kd")_("mRNA") &= (ln(2))/(tau_("mRNA")) \
  alpha &= (a_("tr") dot upright("eff") dot tau_("prot"))/(ln(2) dot upright("KM")) \
  alpha_(0) &= (upright("a0")_("tr") dot upright("eff") dot tau_("prot"))/(ln(2) dot upright("KM")) $

= Reactions

#table(
  columns: (auto, auto, 1fr, 1fr, auto),
  stroke: none,
  align: (left, left, left, left, left),
  table.hline(stroke: 0.8pt),
  table.header([*Rate*], [*Id*], [*Name*], [*Equation*], [*Modifiers*]),
  table.hline(stroke: 0.4pt),
  [$v_("Reaction1")$], [`Reaction1`], [degradation of LacI transcripts], [$X --> emptyset$], [],
  [$v_("Reaction2")$], [`Reaction2`], [degradation of TetR transcripts], [$Y --> emptyset$], [],
  [$v_("Reaction3")$], [`Reaction3`], [degradation of CI transcripts], [$Z --> emptyset$], [],
  [$v_("Reaction4")$], [`Reaction4`], [translation of LacI], [$emptyset --> upright("PX")$], [$X$],
  [$v_("Reaction5")$], [`Reaction5`], [translation of TetR], [$emptyset --> upright("PY")$], [$Y$],
  [$v_("Reaction6")$], [`Reaction6`], [translation of CI], [$emptyset --> upright("PZ")$], [$Z$],
  [$v_("Reaction7")$], [`Reaction7`], [degradation of LacI], [$upright("PX") --> emptyset$], [],
  [$v_("Reaction8")$], [`Reaction8`], [degradation of TetR], [$upright("PY") --> emptyset$], [],
  [$v_("Reaction9")$], [`Reaction9`], [degradation of CI], [$upright("PZ") --> emptyset$], [],
  [$v_("Reaction10")$], [`Reaction10`], [transcription of LacI], [$emptyset --> X$], [$upright("PZ")$],
  [$v_("Reaction11")$], [`Reaction11`], [transcription of TetR], [$emptyset --> Y$], [$upright("PX")$],
  [$v_("Reaction12")$], [`Reaction12`], [transcription of CI], [$emptyset --> Z$], [$upright("PY")$],
  table.hline(stroke: 0.8pt),
)

The rates of the reactions are:

$ v_("Reaction1") &= upright("kd")_("mRNA") dot X \
  v_("Reaction2") &= upright("kd")_("mRNA") dot Y \
  v_("Reaction3") &= upright("kd")_("mRNA") dot Z \
  v_("Reaction4") &= k_("tl") dot X \
  v_("Reaction5") &= k_("tl") dot Y \
  v_("Reaction6") &= k_("tl") dot Z \
  v_("Reaction7") &= upright("kd")_("prot") dot upright("PX") \
  v_("Reaction8") &= upright("kd")_("prot") dot upright("PY") \
  v_("Reaction9") &= upright("kd")_("prot") dot upright("PZ") \
  v_("Reaction10") &= upright("a0")_("tr") + (a_("tr") dot upright("KM")^(n))/(upright("KM")^(n) + upright("PZ")^(n)) \
  v_("Reaction11") &= upright("a0")_("tr") + (a_("tr") dot upright("KM")^(n))/(upright("KM")^(n) + upright("PX")^(n)) \
  v_("Reaction12") &= upright("a0")_("tr") + (a_("tr") dot upright("KM")^(n))/(upright("KM")^(n) + upright("PY")^(n)) $

= ODE system

The states change in time with the rates of the reactions:

$ (dif upright("PX"))/(dif t) &= v_("Reaction4") - v_("Reaction7") \
  (dif upright("PY"))/(dif t) &= v_("Reaction5") - v_("Reaction8") \
  (dif upright("PZ"))/(dif t) &= v_("Reaction6") - v_("Reaction9") \
  (dif X)/(dif t) &= -v_("Reaction1") + v_("Reaction10") \
  (dif Y)/(dif t) &= -v_("Reaction2") + v_("Reaction11") \
  (dif Z)/(dif t) &= -v_("Reaction3") + v_("Reaction12") $
