# -----------------------------------------------------------
# Autogenerated ODE definition from SBML file with sbmlutils.
#
#    model: {{ model.getId() }}
# -----------------------------------------------------------

# -------------------
# ids
# -------------------
xids <- c({% for id in xids %}"{{ id }}"{% if not loop.last %}, {% endif %}{% endfor %})
pids <- c({% for id in pids %}"{{ id }}"{% if not loop.last %}, {% endif %}{% endfor %})
yids <- c({% for id in yids %}"{{ id }}"{% if not loop.last %}, {% endif %}{% endfor %})

# -------------------
# initial conditions
# -------------------
x0 = c(
{% for id in xids %}
  {{ x0[id] }}{% if not loop.last %},{% endif %}      # [{{ loop.index }}] {{ id }}
{% endfor %}
)

# -------------------
# parameters
# -------------------
p = c(
{% for id in pids %}
  {{ p[id] }}{% if not loop.last %},{% endif %}      # [{{ loop.index }}] {{ id }}
{% endfor %}
)

# -------------------
# odes
# -------------------
f_dxdt <- function(t, x, p){
    # ODE system
    {% for id in yids %}
    {{ id }} = {{ y[id] }}      # [{{ loop.index }}] {{ id }}
    {% endfor %}

    # ode
    list(c(
        {% for id in xids %}
        d{{ id }} = {{ dx[id] }}{% if not loop.last %},{% endif %}

        {% endfor %}
    ))
}

f_y <- function(t, x, p){
    # Calculate y

    {% for id in yids %}
    {{ id }} = {{ y[id] }}  # [{{ loop.index }}] {{ id }}
    {% endfor %}

    # --------------------------------------

    y = np.empty(shape=({{yids | length}}))
    c({% for id in yids %}{{ id }}{% if not loop.last %}, {% endif %}{% endfor %})
}


f_z <- function(T, X, p){
    # calculate z
    shape <- dim(X)
    Nt <- shape[1]
    Nx <- shape[2]
    Ny = length(yids)
    Nz = 1 + Nx + Ny
    Z = matrix(, nrow=Nt, ncol=Nz)
    Z[,1] = T
    Z[,2:(Nx+2)] = X
    for (kt in seq(Nt)){
        y = f_y(t=T[kt], x=X[kt, ], p=p)
        Z[kt, (Nx+2):Nz] = y
    }
    colnames(Z) <- c ("time", xids, yids)
    Z
}