# -----------------------------------------------------------
# Autogenerated ODE definition from SBML file with sbmlutils.
#
#    model: {{ model.getId() }}
# -----------------------------------------------------------

# -------------------
# ids
# -------------------
xids <- c({% for id in xids %}"{{ id }}"{% if not loop.last %}, {% endif %}{% endfor %})
pids <- c({% for id in pids %}"{{ id }}"{% if not loop.last %}, {% endif %}{% endfor %})
yids <- c({% for id in yids %}"{{ id }}"{% if not loop.last %}, {% endif %}{% endfor %})

# -------------------
# initial conditions
# -------------------
x0 = c(
{% for id in xids %}
  {{ x0[id] }}{% if not loop.last %},{% endif %}      # [{{ loop.index }}] {{ id }}
{% endfor %}
)

# -------------------
# parameters
# -------------------
p = c(
{% for id in pids %}
  {{ p[id] }}{% if not loop.last %},{% endif %}      # [{{ loop.index }}] {{ id }}
{% endfor %}
)

# -------------------
# odes
# -------------------
f_dxdt <- function(t, x, p){
    # ODE system
    {% for id in yids %}
    {{ id }} = {{ y[id] }}      # [{{ loop.index }}] {{ id }}
    {% endfor %}

    # ode
    list(c(
        {% for id in xids %}
        d{{ id }} = {{ dx[id] }}{% if not loop.last %},{% endif %}

        {% endfor %}
    ))
}
