"""
Autogenerated ODE definition from SBML file with sbmlutils.

    model: {{ model.getId() }}
"""
import numpy as np
import pandas as pd


# -------------------
# ids
# -------------------
xids = [{% for id in xids %}"{{ id }}", {% endfor %}]
pids = [{% for id in pids %}"{{ id }}", {% endfor %}]
yids = [{% for id in yids %}"{{ id }}", {% endfor %}]

# -------------------
# initial conditions
# -------------------
x0 = np.array([
{% for id in xids %}
    {{ x0[id] }},     # [{{ loop.index0 }}] {{ id }}
{% endfor %}
])

# -------------------
# parameters
# -------------------
p = np.array([
{% for id in pids %}
    {{ p[id] }},     # [{{ loop.index0 }}] {{ id }}
{% endfor %}
])


def f_dxdt(x, t, p):
    """ ODE system """
    {% for id in yids %}
    {{ id }} = {{ y[id] }}      # [{{ loop.index0 }}] {{ id }}
    {% endfor %}

    # ode
    return [
        {% for id in xids %}
        {{ dx[id] }},       # [{{ loop.index0 }}] {{ id }}
        {% endfor %}
    ]
